Add placeholders system and use duration for set time in configuration.
EternalCodeTeam/EternalCore pull request #147
Opened 2022-07-08 18:39 UTC by Rollczi

**Please describe the changes made by this PR and why they need to be merged:**

**Status:**

2022-07-08 18:58 UTC, vLuckyyy requested changes

2022-07-08 18:58 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/placeholder/PlaceholderRegistry.java
> +        for (PlaceholderStack stack : stacks) {
this

2022-07-08 18:58 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/placeholder/PlaceholderRegistry.java
> +        for (Map.Entry<String, Placeholder> entry : placeholders.entrySet()) {
this

2022-07-08 18:58 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/placeholder/PlaceholderRegistry.java
> +        for (PlayerPlaceholderStack stack : playerStacks) {
this

2022-07-08 18:58 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/placeholder/PlaceholderRegistry.java
> +        for (Map.Entry<String, PlayerPlaceholder> entry : playerPlaceholders.entrySet()) {
this

2022-07-09 14:17 UTC, vLuckyyy approved these changes

2022-07-09 20:51 UTC, vLuckyyy requested changes

2022-07-09 20:51 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/configuration/composer/DurationComposer.java
> +}
Hm? 
```console
[22:42:50 ERROR]: Error occurred while enabling EternalCore v1.0.0 (Is it up to date?)
java.lang.RuntimeException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at com.eternalcode.core.libs.org.panda.std.Result.orThrow(Result.java:197) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.configuration.ConfigurationManager.loadAndRender(ConfigurationManager.java:55) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.configuration.ConfigurationManager.loadAndRenderConfigs(ConfigurationManager.java:47) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.EternalCore.onEnable(EternalCore.java:236) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-50]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-50]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at com.eternalcode.core.libs.org.panda.std.Result.mapErr(Result.java:122) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:71) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.lambda$load$1(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.load(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.configuration.ConfigurationManager.loadAndRender(ConfigurationManager.java:54) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        ... 13 more
Caused by: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at com.eternalcode.core.libs.org.panda.std.Result.mapErr(Result.java:122) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:58) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.composers.ContextualComposer.deserialize(ContextualComposer.java:35) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserializeMember$6(CdnDeserializer.java:156) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeMember(CdnDeserializer.java:156) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeToSection(CdnDeserializer.java:84) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:62) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.lambda$load$1(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.load(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.configuration.ConfigurationManager.loadAndRender(ConfigurationManager.java:54) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        ... 13 more
Caused by: com.eternalcode.core.libs.net.dzikoysk.cdn.CdnException: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at com.eternalcode.core.libs.org.panda.std.Result.mapErr(Result.java:122) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:71) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserialize$1(CdnDeserializer.java:57) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:57) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.composers.ContextualComposer.deserialize(ContextualComposer.java:35) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserializeMember$6(CdnDeserializer.java:156) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeMember(CdnDeserializer.java:156) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeToSection(CdnDeserializer.java:84) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:62) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.lambda$load$1(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.org.panda.std.Result.flatMap(Result.java:128) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.libs.net.dzikoysk.cdn.Cdn.load(Cdn.java:87) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        at com.eternalcode.core.configuration.ConfigurationManager.loadAndRender(ConfigurationManager.java:54) ~[EternalCore v1.0.0 (MC 1.17-1.18x).jar:?]
        ... 13 more
Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at java.time.Duration.parse(Duration.java:419) ~[?:?]
        at com.eternalcode.core.configuration.composer.DurationComposer.lambda$deserialize$0(DurationComposer.java:13) ~[EternalCore v1.0.0 (MC 1.17-1 [...]

2022-07-09 20:51 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
> +        if (environment.isVersion(17)) {
To chyba nie powinno tak działać
Sprawdzasz czy wersja == 1.17

Tutaj log z konsoli 
```console
[22:42:50 WARN]: [EternalCore] EternalCore no longer supports your version, be aware that there may be bugs!
```

2022-07-09 20:57 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/configuration/composer/DurationComposer.java
> +}
nie używaj starej konfiguracji

2022-07-21 23:19 UTC, merged