Refactor config system
EternalCodeTeam/EternalCore pull request #182
Opened 2022-08-27 18:32 UTC by vLuckyyy

**Please describe the changes made by this PR and why they need to be merged: Generally refactored configuration system for EternalCore**

**Status: Successfully and tested**

2022-08-28 14:03 UTC, Osnixer requested changes
Mogłem nie trafić gdzieś dokładnie w linijkę bo review z telefonu leci

2022-08-28 14:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
To samo na górę

2022-08-28 14:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
> +    public Resource resource(File folder) {
To samo na górę

2022-08-28 14:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/configuration/language/LanguageConfiguration.java
> +    public Resource resource(File folder) {
Up!

2022-08-29 13:39 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/CommandsConfiguration.java
> -        public Map<String, String> commands = new ImmutableMap.Builder<String, String>()
I tak wygląda to na moment aktualny inaczej nie ma już placeholderów + nie wiadomo kiedy rollczi sie za to weźmie

2022-08-29 14:04 UTC, Osnixer submitted a review, later dismissed

2022-08-29 14:04 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
> +            .typeBind(EternalCore.class, () -> this)
where spacje przed () ->

2022-08-29 14:50 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
> +                """;
sus

2022-08-31 18:32 UTC, Osnixer approved these changes

2022-08-31 18:32 UTC, merged