Add option to customize command name, aliases and permissions.
EternalCodeTeam/EternalCore pull request #188
Opened 2022-09-03 18:26 UTC by Rollczi

**Please describe the changes made by this PR and why they need to be merged:**

**Status:**

2022-09-03 19:40 UTC, Osnixer requested changes

2022-09-03 19:40 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/configurator/CommandConfigurator.java
> +        CommandConfiguration.Command command = commandConfiguration.commands.get(state.getName());
ewidentnie brakuje tutaj jednego słówka

2022-09-03 19:40 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/configurator/CommandConfiguration.java
> +    public Resource resource(File folder) {
zachowałbym strukturę innych plików konfiguracyjnych i dał to na samą górę ;)

2022-09-03 19:41 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/command/configurator/CommandConfigurator.java
> +        CommandConfiguration.Command command = commandConfiguration.commands.get(state.getName());
this

2022-09-03 20:45 UTC, vLuckyyy approved these changes

2022-09-04 18:42 UTC, Osnixer approved these changes

2022-09-04 18:43 UTC, merged