Fix open inventory options
EternalCodeTeam/EternalCore pull request #193
Opened 2022-09-07 16:50 UTC by vLuckyyy

2022-09-07 18:56 UTC, Jakubk15 reviewed
imo jest ok, ale osoby działające na zwykłym Spigotcie nie skorzystają na tym. Z drugiej strony zdecydowanie większość osób korzysta z Papera lub jego forków, no chyba że zrobimy checka, że gdy na serwerze jest paper to zostanie otworzone dane GUI Paperlibem, a jak nie to klasyczną metodą.

2022-09-09 14:15 UTC, Jakubk15 requested changes

2022-09-09 14:15 UTC, Jakubk15 commented on eternalcore-paper/src/main/java/com/eteranlcode/containers/AdditionalContainerPaper.java
> +    private static final Environment environment = PaperLib.getEnvironment();
Zmienna `enviroment` jest używana tylko raz, więc po co ją tworzyć, lepiej bezpośrednio użyć `PaperLib#getEnviroment()`

2022-09-09 14:15 UTC, Jakubk15 commented on eternalcore/build.gradle.kts
> +        "com.eteranlcode.containers"
literówka, powinno być `com.eternalcode.containers`

2022-09-09 14:16 UTC, Jakubk15 commented on eternalcore-paper/src/main/java/com/eteranlcode/containers/AdditionalContainerPaper.java
> +    private static final Environment environment = PaperLib.getEnvironment();
to jest tylko moja sugestia, także jeżeli wolisz aby kod był "czystszy" kliknij "Resolve conversation"

2022-09-09 14:18 UTC, Jakubk15 commented on eternalcore-paper/src/main/java/com/eteranlcode/containers/AdditionalContainerPaper.java
> +            player.sendMessage(ChatColor.RED + "Anvil command feature is not supported on this server. Please contact the server administrator and check console!");
Czy to jest dobry pomysł? Ludzie mogą to wykorzystać, spamować tą komendą aby wywołać spam w konsoli

2022-09-09 20:03 UTC, Osnixer requested changes

2022-09-09 20:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/StonecutterCommand.java
> +    private final Plugin plugin;
plugin -> Logger

2022-09-09 20:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/GrindstoneCommand.java
> +    private final Plugin plugin;
plugin -> Logger

2022-09-09 20:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/CartographyTableCommand.java
> +    private final Plugin plugin;
plugin -> Logger

2022-09-09 20:03 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/AnvilCommand.java
> +    private final Plugin plugin;
plugin -> Logger

2022-09-09 20:05 UTC, Jakubk15 commented on eternalcore-paper/src/main/java/com/eteranlcode/containers/AdditionalContainerPaper.java
> +            player.sendMessage(ChatColor.RED + "Thus feature is not supported on this server. Please contact the server administrator and check console!");
literówka chyba

2022-09-09 20:06 UTC, Osnixer approved these changes

2022-09-09 20:08 UTC, Jakubk15 approved these changes

2022-09-09 20:37 UTC, merged