Update BenchmarkUtils and GarbageCollectorCommand
EternalCodeTeam/EternalCore pull request #21
Opened 2021-12-28 21:24 UTC by vLuckyyy

2021-12-29 22:02 UTC, Rollczi requested changes

2021-12-29 22:02 UTC, Rollczi commented on src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
> +        String[] tpsAvg = Arrays.stream(tps).mapToObj(BenchmarkUtils::format).toArray(String[]::new);
jest jakiś collector łączący stringi ze streama.
Coś w stylu
`return Arrays.stream(tps).mapToObj(BenchmarkUtils::format).collect(Collectors.join(// jakieś argumenty //))`

2021-12-29 22:12 UTC, zitreF commented on src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
> +        String[] tpsAvg = Arrays.stream(tps).mapToObj(BenchmarkUtils::format).toArray(String[]::new);
Collectors.joining(", ");
mozna tez String#join ale lepiej w tym przypadku uzyc tego powyzej

2021-12-30 01:41 UTC, vLuckyyy commented on src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
> +        return ((tps > 18.0) ? ChatColor.GREEN : (tps > 16.0) ? ChatColor.YELLOW : ChatColor.RED)
```java
    public static String getTPS() {
        return Arrays.stream(Bukkit.getTPS()).mapToObj(TPSUtils::format).collect(Collectors.joining(", "));
    }
```

Powinno być git.

2021-12-30 01:42 UTC, vLuckyyy commented on src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
> +        String[] tpsAvg = Arrays.stream(tps).mapToObj(BenchmarkUtils::format).toArray(String[]::new);
```java
    public static String getTPS() {
        return Arrays.stream(Bukkit.getTPS()).mapToObj(TPSUtils::format).collect(Collectors.joining(", "));
    }
```

Powinno być git.

2021-12-30 03:28 UTC, merged