Refactor String -> Notification, Fixed pattern in NotificationComposer, and a bit messages recactor
EternalCodeTeam/EternalCore pull request #231
Opened 2022-12-12 20:26 UTC by Osnixer

2022-12-13 00:40 UTC, vLuckyyy requested changes
Dzień dobry kierowniku, proszę naprawić najpierw budowanie się projektu. Później pomyślimy o reszcie.

👇
![image](https://user-images.githubusercontent.com/65517973/207198081-582e3934-a8cb-45e9-8aa7-6c38b6a191a9.png)

2022-12-15 20:09 UTC, iNyatix submitted a review, later dismissed

2022-12-16 21:55 UTC, vLuckyyy approved these changes

2022-12-16 22:03 UTC, Rollczi requested changes

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/item/ItemLoreCommand.java
> +        return itemStack;
w sumie trochę taka nie oczywista ta metoda bo wysyła jeszcze wiadomość
możesz ją wysłać  tenoticeService.player i po if (itemStack == null

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/command/implementation/item/ItemNameCommand.java
> +    private ItemStack validateItemFromMainHand(Player player) {
tak samo

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/request/TpaAcceptCommand.java
> +            this.noticeService
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportBackCommand.java
> +        this.noticeService.create()
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportBackCommand.java
> +            this.noticeService.create()
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportBackCommand.java
> +
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportBackCommand.java
> +            this.noticeService.create()
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/teleport/request/TpaAcceptCommand.java
> +        this.noticeService
tu już możesz tenoticeService.player

2022-12-16 22:03 UTC, Rollczi commented on eternalcore/src/test/java/com/eternalcode/core/configuration/composer/NotificationComposerTest.java
> +class NotificationComposerTest {
😎

2022-12-17 19:41 UTC, Rollczi approved these changes

2022-12-17 19:41 UTC, merged