GH-243 Improve comments in config file (Resolve #239, #240)
EternalCodeTeam/EternalCore pull request #243
Opened 2022-12-26 18:30 UTC by vLuckyyy

#239 #240

2022-12-27 08:31 UTC, Jakubk15 requested changes

2022-12-27 08:31 UTC, Jakubk15 commented on eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PlaceholdersConfiguration.java
> +        "# An example is {prefix}, wherever you use {prefix} the specified value will be displayed",
```suggestion
        "# An example is {prefix}, whenever you use {prefix} the specified value will be displayed",
```

2022-12-27 14:24 UTC, Jakubk15 approved these changes

2022-12-28 21:27 UTC, Osnixer requested changes

2022-12-28 21:27 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/LocationsConfiguration.java
> +    @Description("# Don't touch this")
nazwałbym to raczej po prostu spawn location/position etc

2022-12-28 21:27 UTC, Osnixer commented on eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/LocationsConfiguration.java
>      public Map<String, Position> warps = new HashMap<>();
dodałbym komentarz coś typu "pozycje warpów"

2022-12-30 16:18 UTC, Rollczi approved these changes

2022-12-30 16:53 UTC, merged