GH-253 Add necessary checks to ignore/unignore feature (Resolve #252, #251)
EternalCodeTeam/EternalCore pull request #253
Opened 2022-12-28 20:00 UTC by eripe14

2022-12-29 16:58 UTC, vLuckyyy approved these changes

2022-12-30 15:41 UTC, Rollczi requested changes

2022-12-30 15:41 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreCommand.java
> +
tego ifa daj przed wykonaniem this.repository.isIgnored()

2022-12-30 15:41 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
> +            }
tego ifa daj przed wykonaniem this.repository.isIgnored()

2022-12-30 15:41 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
> +            if (isIgnored) {
!isIgnored

2022-12-30 15:41 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/privatechat/PrivateChatCommand.java
> +        }
to się imo przydaje w testach kolorków itd

2023-01-02 20:40 UTC, vLuckyyy approved these changes

2023-01-03 20:26 UTC, Rollczi approved these changes

2023-01-03 20:28 UTC, merged