Add target check to open inventory command
EternalCodeTeam/EternalCore pull request #263
Opened 2022-12-28 22:31 UTC by vLuckyyy

This PR fixes a critical bug where you could copy your items by opening your inventory

2022-12-29 08:01 UTC, Jakubk15 approved these changes

2022-12-30 15:36 UTC, Rollczi requested changes

2022-12-30 15:36 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
> +        Notification cantOpenYourInventory();
proszę nie dodwać wiadomości do OtherMessages

2022-12-30 17:34 UTC, Rollczi approved these changes

2022-12-30 17:35 UTC, merged