GH-270 Exclude NONE from NoticeType argument tabulation (Resolve #249)
EternalCodeTeam/EternalCore pull request #270
Opened 2022-12-29 00:45 UTC by eripe14

2022-12-29 00:52 UTC, vLuckyyy requested changes
Dodaj do changelogu

2022-12-29 00:55 UTC, vLuckyyy approved these changes

2022-12-29 14:37 UTC, vLuckyyy requested changes

2022-12-29 14:37 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/command/argument/NoticeTypeArgument.java
> +import java.util.stream.Stream;
Usuń tego zbędnego importa

2022-12-30 15:09 UTC, Rollczi approved these changes

2022-12-30 15:10 UTC, vLuckyyy approved these changes

2022-12-30 15:10 UTC, merged