Add option to ignore and unignore all.
EternalCodeTeam/EternalCore pull request #293
Opened 2023-01-09 20:41 UTC by Rollczi

2023-01-09 21:11 UTC, Osnixer approved these changes
Jak dla mnie clean

2023-01-10 00:04 UTC, Rollczi commented
Teraz pytanie czy działa

2023-01-10 06:24 UTC, vLuckyyy requested changes

2023-01-10 06:24 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreCommand.java
> +    @Execute(route = "*")
Proponuje dodać alias "all"

2023-01-10 06:24 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
> +    @Execute(route = "*")
Proponuje dodać alias "all"

2023-01-10 06:24 UTC, vLuckyyy commented on eternalcore/src/main/java/com/eternalcode/core/database/wrapper/IgnoreRepositoryOrmLite.java
> +    private static final UUID IGNORE_ALL = UUID.fromString("*");
To nie zadziała

2023-01-10 07:47 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreCommand.java
> +    @Execute(route = "*")
taki nick może istnieć na serwerze będzie kolidować

2023-01-10 07:47 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
> +    @Execute(route = "*")
taki nick może istnieć na serwerze, będzie kolidować

2023-01-10 07:47 UTC, Rollczi commented on eternalcore/src/main/java/com/eternalcode/core/database/wrapper/IgnoreRepositoryOrmLite.java
> +    private static final UUID IGNORE_ALL = UUID.fromString("*");
Naprawione

2023-01-10 17:40 UTC, vLuckyyy approved these changes
Approve, przetestowane za pomocą niezawodnego teamu.
![image](https://user-images.githubusercontent.com/65517973/211623408-4a353a91-c18e-44b4-95b9-fc8ecae34edb.png)

2023-01-10 21:18 UTC, merged