Add language support to world and location argument
EternalCodeTeam/EternalCore pull request #302
Opened 2023-01-19 21:00 UTC by eripe14

2023-01-19 21:13 UTC, vLuckyyy approved these changes

2023-01-21 14:23 UTC, vLuckyyy requested changes
Proszę dodać to do changelogs.md

2023-01-21 17:15 UTC, Jakubk15 requested changes

2023-01-21 17:15 UTC, Jakubk15 commented on eternalcore/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
> +        public Notification youMustGiveWorldName = Notification.chat("<dark_gray>» <red>You must give world name!");
```suggestion
        public Notification youMustGiveWorldName = Notification.chat("<dark_gray>» <red>You must provide a world name!");
```

2023-01-21 17:52 UTC, vLuckyyy approved these changes

2023-01-21 19:48 UTC, Jakubk15 approved these changes

2023-01-21 19:48 UTC, merged