Dependency manager
EternalCodeTeam/EternalCore pull request #305
Opened 2023-01-21 12:30 UTC by vLuckyyy

**Status: WORKING IN PROGRES**

2023-01-22 16:50 UTC, Jakubk15 commented on README.md
> +# Information's
```suggestion
# Informations
```

2023-01-22 16:50 UTC, Jakubk15 commented on eternalcore/build.gradle.kts
> +        "javax/**",
ten `,` chyba tutaj useless

2023-01-30 00:37 UTC, Osnixer approved these changes

2023-01-30 16:45 UTC, Osnixer requested changes
fix

2023-02-15 02:16 UTC, closed without merging