Rename modules and add buildSrc module
EternalCodeTeam/EternalCore pull request #307
Opened 2023-01-21 13:19 UTC by vLuckyyy

- Add buildSrc module for easier management and centralization of code from modules.
- Rename eternalcore -> core
- Rename eternalcore-paper -> paper

2023-01-21 17:02 UTC, Jakubk15 requested changes
nic mi nie mówi to co napisałeś na dc w tldr, na spotkaniu mi dokładniej wyjaśnisz

2023-01-21 17:02 UTC, Jakubk15 commented on buildSrc/src/main/kotlin/com.eternalcode.java-conventions.gradle.kts
> +    maven { url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/") }
simplify maven

2023-01-21 17:03 UTC, vLuckyyy commented on buildSrc/src/main/kotlin/com.eternalcode.java-conventions.gradle.kts
> +    maven { url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/") }
???

2023-01-21 17:04 UTC, vLuckyyy commented
> nic mi nie mówi to co napisałeś na dc w tldr, na spotkaniu mi dokładniej wyjaśnisz

Pozwala do ogranizacji i centralizacji kodu, gdy nie wiesz o co chodzi to nie rób requested changes.

2023-01-21 22:52 UTC, eripe14 approved these changes
LGTM

2023-01-21 23:25 UTC, Osnixer approved these changes

2023-01-22 00:56 UTC, Rollczi approved these changes

2023-01-22 00:56 UTC, merged