Add check that spawn is not set yet
EternalCodeTeam/EternalCore pull request #342
Opened 2023-02-07 20:58 UTC by vLuckyyy

2023-02-07 21:06 UTC, Rollczi requested changes

2023-02-07 21:06 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
> +        if (world == null || world.getName().equals("__NONE__")) {
Wywal __NONE__ do zmiennej statycznej w Position

2023-02-08 00:08 UTC, Kamicjusz approved these changes

2023-02-08 01:00 UTC, Rollczi requested changes

2023-02-08 01:00 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/configuration/implementation/LocationsConfiguration.java
> +    public Position spawn = new Position(0, 0, 0, 0.0f, 0.0f, "__NONE__");
Position.NONE_WORLD użyj

2023-02-11 17:29 UTC, Rollczi approved these changes

2023-02-11 19:43 UTC, eripe14 approved these changes

2023-02-11 19:43 UTC, Osnixer approved these changes
PIĘKNIAŚTY KODZIK, APROH!

2023-02-11 19:43 UTC, merged