feature/add-features-to-readme
EternalCodeTeam/EternalCore pull request #353
Opened 2023-02-12 18:07 UTC by Jakubk15

Closes #337

2023-02-13 19:59 UTC, vLuckyyy commented on README.md
> +- Chat manager, including:
nazwij to ChatFeatures, bo helpop nie jest chat manager

2023-02-13 19:59 UTC, vLuckyyy commented on README.md
> +- Admin chat
To przerzuć do chat features

2023-02-13 19:59 UTC, vLuckyyy commented on README.md
> +- Switch gamemodes easily
To można usunąć bo to w normalnym mc jest to w sumie wiesz xd

2023-02-13 20:00 UTC, vLuckyyy commented on README.md
> +- Home and warp system
Dodaj info o /spawn

2023-02-19 14:48 UTC, vLuckyyy requested changes

2023-02-19 14:48 UTC, vLuckyyy commented on README.md
> +- Adventure and MiniMessage integration
Dopisz tutaj jeszcze że wspieramy zmiane gdzie wiadomość ma zostać wysłana oraz że wspieramy legacy kolorki i mergujemy!

2023-02-19 17:47 UTC, Jakubk15 commented on README.md
> +- Adventure and MiniMessage integration
done

2023-02-19 19:03 UTC, vLuckyyy approved these changes

2023-02-19 19:03 UTC, merged