Add more description about functions in configs.
EternalCodeTeam/EternalCore pull request #358
Opened 2023-02-14 23:01 UTC by vLuckyyy

2023-02-22 01:53 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/listener/player/PlayerJoinListener.java
> -        if (this.config.otherSettings.gameModeOnJoin) {
NIe powiązane zmiany

2023-02-25 20:31 UTC, Rollczi commented
napraw konflikty

2023-03-03 18:35 UTC, Jakubk15 approved these changes

2023-03-03 18:35 UTC, Jakubk15 commented on core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
>          public int clearLines = 128;
zmieniłbym to w sumie na `linesToClear`

2023-03-05 14:04 UTC, Jakubk15 commented
Podoba mi się, dobra robota Martin

2023-03-05 14:06 UTC, Kryspek approved these changes
Good job Lucky <3

2023-03-11 20:05 UTC, Kamicjusz approved these changes

2023-03-11 20:47 UTC, Osnixer approved these changes
Bardzo ładny pr-ek, styl wiadomości przejrzysty i bardzo prosty

2023-03-11 21:07 UTC, Rollczi requested changes

2023-03-11 21:07 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> +        public Notification noCommand = Notification.chat("<dark_gray>» <red>Komenda <yellow>{COMMAND} <red>nie istnieje!");
commandNotFound

2023-03-11 21:07 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
>          @Description({ " ", "# Custom message for unknown command" })
replaceStandardHelpMessage

2023-03-12 19:44 UTC, eripe14 approved these changes

2023-03-14 00:32 UTC, Osnixer approved these changes

2023-03-15 21:13 UTC, merged