GH-359 Add reply to target
EternalCodeTeam/EternalCore pull request #360
Opened 2023-02-19 09:31 UTC by Jakubk15

Resolves #347

2023-02-20 21:09 UTC, vLuckyyy requested changes
Super, tylko musisz dodać to jeszcze w komendach speed, repair oraz komend od kontenerów, anvil etc

2023-02-20 21:21 UTC, Jakubk15 commented
> Super, tylko musisz dodać to jeszcze w komendach speed, repair oraz komend od kontenerów, anvil etc

Z tego co widziałem to tam jest już to zaimplementowane.

2023-02-20 21:27 UTC, vLuckyyy commented
> > Super, tylko musisz dodać to jeszcze w komendach speed, repair oraz komend od kontenerów, anvil etc
> 
> Z tego co widziałem to tam jest już to zaimplementowane.

W kontenerach nie ma
```java
package com.eternalcode.core.feature.essentials.container;

import com.eternalcode.containers.AdditionalContainerPaper;
import com.eternalcode.containers.AdditionalContainerType;
import dev.rollczi.litecommands.argument.Arg;
import dev.rollczi.litecommands.argument.By;
import dev.rollczi.litecommands.command.execute.Execute;
import dev.rollczi.litecommands.command.permission.Permission;
import dev.rollczi.litecommands.command.route.Route;
import org.bukkit.entity.Player;

@Route(name = "anvil")
@Permission("eternalcore.anvil")
public class AnvilCommand {

    @Execute
    void executeSelf(Player player) {
        AdditionalContainerPaper.openAdditionalContainer(player, AdditionalContainerType.ANVIL);
    }

    @Execute
    void execute(@Arg Player target) {
        AdditionalContainerPaper.openAdditionalContainer(target, AdditionalContainerType.ANVIL);
    }

}

```

2023-02-21 08:33 UTC, Jakubk15 commented
Ok, a mam to dodać tylko dla targetu, czy również dla command invokera? Można też zrobić tak, że w configu będzie można zdecydować czy wiadomości dla targetu mają być wysyłane.

2023-02-21 15:24 UTC, vLuckyyy commented
> Ok, a mam to dodać tylko dla targetu, czy również dla command invokera? Można też zrobić tak, że w configu będzie można zdecydować czy wiadomości dla targetu mają być wysyłane.

Tu i tu, żeby nie było żadnych ograniczeń oraz jak ktoś nie będzie chciał wiadomości to po prostu ustawi typ notyfikacji na [NONE]

2023-02-21 20:03 UTC, vLuckyyy approved these changes
Jest spoko, ale proponuje zachować standardowe nazwy, invoker -> player/sender 
announcer -> noticeService, tak jak w większości klas.

2023-02-22 01:56 UTC, Rollczi approved these changes

2023-02-23 02:54 UTC, vLuckyyy approved these changes

2023-02-23 03:02 UTC, merged