Use mockito for PrepareUserControllerTest
EternalCodeTeam/EternalCore pull request #373
Opened 2023-03-02 18:56 UTC by vLuckyyy

2023-03-03 06:12 UTC, Rollczi requested changes
Okej, użyte ale nie przesadzaj z mockowaniem w miejscach które tego nie wymagają

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +    private UserManager userManager;
nie mockuj, tylko komplikujesz

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        User user = mock(User.class);
nie mockuj też usera

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        verify(user).setClientSettings(any(ClientBukkitSettings.class));
też komplikujesz, nie ma potrzeby sprawdzania invokacji jeśli dane są normalnie dostępne

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        verify(user).setClientSettings(ClientSettings.NONE);
tu tak samo

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        when(this.userManager.getUser(FAKE_UUID)).thenReturn(Option.of(user));
tu też

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        when(this.userManager.getUser(FAKE_UUID)).thenReturn(Option.of(user));
tu też

2023-03-03 06:12 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        verify(user).setClientSettings(ClientSettings.NONE);
tu też

2023-03-03 06:15 UTC, Rollczi requested changes

2023-03-03 06:15 UTC, Rollczi commented on core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
> +        MockitoAnnotations.openMocks(this);
zamykaj mockito, to co zwraca `openMocks(this)` zapisujesz do fielda i zamykasz `.close()`

2023-03-04 14:57 UTC, Osnixer approved these changes

2023-03-04 14:58 UTC, merged