Add implementation of Apache Commons IO library and create a backup of the configuration files in a new folder with the current date as name and keep only the backups from the last 3 days
EternalCodeTeam/EternalCore pull request #380
Opened 2023-03-14 01:14 UTC by vLuckyyy

https://user-images.githubusercontent.com/65517973/224866872-44a2aeaf-d9fd-4ff7-b12c-419e80ec532a.mp4

2023-03-15 21:28 UTC, Osnixer requested changes

2023-03-15 21:28 UTC, Osnixer commented on core/src/main/java/com/eternalcode/core/configuration/ConfigurationBackupService.java
> +    private static final LocalDate BACKUP_DATE = LocalDate.now();
Przy założeniu że serwer nie będzie restartowany data zostanie taka sama przez np. 2 dni, ta data powinna być w kodzie.

2023-03-15 21:28 UTC, Osnixer commented on core/src/main/java/com/eternalcode/core/configuration/ConfigurationManager.java
>      private final Cdn cdn = CdnFactory
where big capitals :angry_pepe:

2023-03-16 19:12 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/configuration/ConfigurationBackupService.java
> +                }
proponuję wydzielić do metody: this.copyToBackupFile(targetFolder, file);

2023-03-19 14:48 UTC, Osnixer approved these changes

2023-03-19 14:52 UTC, Rollczi approved these changes

2023-03-19 14:53 UTC, merged