GH-386 Added TpUpCommand
EternalCodeTeam/EternalCore pull request #386
Opened 2023-03-27 17:35 UTC by failutee

## Description

The update introduces the '/tpup' command, which teleports the player to the highest block above them.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

The tests have been conducted on a local server.

Instruction:
  - Run the /tpup command

_After executing the command, the player should appear on the block that is highest above their head._

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to readme etc.
- [x] My changes generate no new warnings

2023-03-27 17:55 UTC, vLuckyyy approved these changes
Thank you for submitting the PR! I've tested it and it works perfectly. Great job! Your contribution is much appreciated. I hereby approve the PR

2023-03-27 18:40 UTC, Jakubk15 approved these changes

2023-03-27 18:40 UTC, Jakubk15 commented on core/src/main/java/com/eternalcode/core/teleport/command/TeleportUpCommand.java
> +@Route(name = "tpup")
```suggestion
@Route(name = "tpup", aliases = { "up", "teleportup" })
```

2023-03-27 19:30 UTC, Osnixer approved these changes
Great job, thanks for adding something from yourself!

2023-03-27 22:00 UTC, Rollczi requested changes

2023-03-28 08:46 UTC, failutee commented on core/src/main/java/com/eternalcode/core/teleport/command/TeleportUpCommand.java
> +    void teleportPlayerToHighestBlock(Player player) {
Faktycznie, chciałem zachować code style i o tym zapomniałem

2023-03-28 08:55 UTC, failutee commented on core/src/main/java/com/eternalcode/core/teleport/command/TeleportUpCommand.java
> +        newLocation.setYaw(playerLocation.getYaw());
W twojej zmianie klonujesz lokalizacje gracza a następnie dodajesz (0.5, 1, 0.5) co może spowodować przesunięcie lokalizacji na inny blok

2023-03-28 13:38 UTC, Rollczi commented on core/src/main/java/com/eternalcode/core/teleport/command/TeleportUpCommand.java
> +        newLocation.setYaw(playerLocation.getYaw());
Fakty

2023-03-28 13:39 UTC, Rollczi approved these changes

2023-03-28 16:03 UTC, merged