Dependency loader
EternalCodeTeam/EternalCore pull request #396
Opened 2023-04-08 16:54 UTC by Rollczi

2023-04-08 21:10 UTC, Osnixer approved these changes
Bardzo ładna robota

2023-04-08 21:10 UTC, Osnixer commented on plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java
> +    private final LinkedHashSet<Dependency> fullScannedDependencies = new LinkedHashSet<>();
-> private final Set<Dependency> fullScannedDependencies = new LinkedHashSet<>();

2023-04-09 07:08 UTC, Jakubk15 approved these changes
Sporo zmian, szacun za podjęcie się tego, nie mogłem wyłapać żadnych innych błędów, napraw tylko kompilację. Z pewnością będzie jeszcze trzeba to przetestować, jak z wydajnością, itp. Powiedz mi jeszcze czy udało ci się rozwiązać to w taki sposób, aby nie pobierało 2x biblioteki z maven central czy coś w tym stylu, pamiętasz o co mi chodzi chyba. Na dc o tym rozmawialiśmy 😸

2023-04-09 17:36 UTC, vLuckyyy requested changes
Zaktualizuj CI do swoich zmian

2023-04-10 09:46 UTC, eripe14 approved these changes

2023-04-10 14:50 UTC, Rollczi commented on buildSrc/build.gradle.kts
> +        groovy.setSrcDirs(emptyList<String>())
ustawia to wszystkie src dirs dla javy, a w tym wypadku nie ma ani javy ani groovy ani innych rzeczy, więc żeby inteliJ nie generował nie potrzebnych dir to je wywalam

2023-04-10 14:51 UTC, Rollczi commented on buildSrc/src/main/kotlin/eternalcode-java-test.gradle.kts
> +    id("xyz.jpenilla.run-paper")
nie jest ona ustalana odgórnie w pliku zarządzającym lokalnymi pluginami

2023-04-10 14:52 UTC, Rollczi commented on buildSrc/src/main/kotlin/eternalcode-java.gradle.kts
> +    targetCompatibility = JavaVersion.VERSION_17
nie znam się w tym temacie, rozwiń to i też pokaż kodzik

2023-04-10 15:03 UTC, Rollczi commented on plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java
> +    private final LinkedHashSet<Dependency> fullScannedDependencies = new LinkedHashSet<>();
implementacja została celowo oznaczona w sygnaturach fieldów i metod, aby zaznaczyć, że dependencies są poukładane w kolejności załadowania i są również niezduplikowane, tak samo jak w klasie `DependencyLoadResult`
```java
public record DependencyLoadResult(IsolatedClassLoader loader, LinkedHashSet<Dependency> dependencies, List<Path> paths) {
}
```

2023-04-10 15:12 UTC, vLuckyyy commented on buildSrc/src/main/kotlin/eternalcode-java.gradle.kts
> +    targetCompatibility = JavaVersion.VERSION_17
```java
java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
```

Różnica jest taka że ^ jest nowym formatem z wykorzystaniem nowego api, a to co jest obecnie jest starszym formatem

2023-04-10 15:32 UTC, vLuckyyy requested changes
Kod nie funkcjonuje, jeżeli to wina po mojej stronie poproszę wyjaśnij jak to naprawić, bym mógł to przetestowac 👍 

![image](https://user-images.githubusercontent.com/65517973/230933369-58d214f1-016f-4a41-80e8-fca174898b16.png)

2023-04-10 15:40 UTC, Rollczi commented
masz rację po ostatnich zmianach coś zepsułem, właśnie przepisuje system na ładniejszy

2023-04-10 16:54 UTC, Rollczi commented
Gotowe, proszę o pełne review

2023-04-10 17:01 UTC, Osnixer approved these changes

2023-04-10 17:06 UTC, Jakubk15 approved these changes

2023-04-10 17:06 UTC, Jakubk15 commented on buildSrc/src/main/kotlin/eternalcode-paper-run.gradle.kts
> +        minecraftVersion("1.19.3")
```suggestion
        minecraftVersion("1.19.4")
```

2023-04-10 17:06 UTC, Jakubk15 commented on eternalcore-api/build.gradle.kts
> +    compileOnly("org.spigotmc:spigot-api:1.19.3-R0.1-SNAPSHOT")
```suggestion
    compileOnly("org.spigotmc:spigot-api:1.19.4-R0.1-SNAPSHOT")
```

2023-04-10 17:06 UTC, Jakubk15 commented on eternalcore-plugin/build.gradle.kts
> +        archiveFileName.set("EternalCore v${project.version} (MC 1.17-1.19x).jar")
```suggestion
        archiveFileName.set("EternalCore v${project.version} (MC 1.17.x-1.19.x).jar")
```

2023-04-10 17:22 UTC, vLuckyyy approved these changes

2023-04-10 19:21 UTC, Jakubk15 approved these changes

2023-04-10 19:23 UTC, vLuckyyy approved these changes

2023-04-10 19:27 UTC, merged