Separate spawn command functions
EternalCodeTeam/EternalCore pull request #412
Opened 2023-04-14 21:39 UTC by Kamicjusz

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to readme etc.
- [ ] My changes generate no new warnings
- [ ] I have added test to cover my changes
- [ ] I have added appropriate labels to this Pull Request

2023-04-14 21:48 UTC, Rollczi requested changes

2023-04-14 21:48 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
> +    void execute(Player sender, @Arg Player player) {
Viewer a nie Player

2023-04-15 09:12 UTC, Osnixer approved these changes

2023-04-15 13:14 UTC, vLuckyyy approved these changes

2023-04-15 15:27 UTC, Rollczi requested changes

2023-04-15 15:27 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/viewer/BukkitViewerImpl.java
> +        return Bukkit.getServer().getOfflinePlayer(uuid).getName();
`getOfflinePlayer` jest operacją blokującą zrób getPlayer i jeśli jest null to throw ISE z info, że gracz jest offline

2023-04-15 15:27 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
> +            .placeholder("{PLAYER}", viewer.getName())
{PLAYER} jest nieadekwatny tutaj jeśli to consolka mogła wysłać

2023-04-15 15:27 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
> +    void execute(Viewer viewer, @Arg Player player) {
```suggestion
    void execute(Viewer sender, @Arg Player player) {
```

2023-04-15 21:51 UTC, vLuckyyy requested changes

2023-04-15 21:51 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/viewer/BukkitViewerImpl.java
> +        }
checkstyle tego nie przepuści

2023-04-15 21:53 UTC, Osnixer approved these changes

2023-04-15 22:18 UTC, vLuckyyy approved these changes

2023-04-16 00:00 UTC, Rollczi requested changes

2023-04-16 00:00 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/viewer/BukkitViewerImpl.java
> +        }
```suggestion
        
        return player.getName();
```

2023-04-16 00:03 UTC, Rollczi approved these changes

2023-04-16 00:06 UTC, merged