GH-427 Poll system
EternalCodeTeam/EternalCore pull request #427
Opened 2023-04-19 19:37 UTC by failutee

## Krótki opis systemu ankiet
Zmiana wprowadza system który umożliwia tworzenie _ankiet_ z różnymi opcjami.

2023-04-25 00:45 UTC, Osnixer approved these changes

2023-04-25 00:45 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/Poll.java
> +        this.totalVotes = new AtomicInteger();
po co ci ten atoimicInteger cały czas

2023-04-25 00:45 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollInventory.java
> +public class PollInventory {
Przydało by się aby wszystkie itemki do ustawienia w gui były zawarte w configu tak samo jak nazwy itemów oraz lore

2023-04-25 00:45 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/validation/PollDescriptionArgumentValidation.java
> +        }
codeStyle - spacje

2023-04-25 00:45 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/validation/PollOptionListArgumentValidation.java
> +        poll.setOptionList(options);
codeStyle - spacje

2023-04-25 00:45 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollController.java
> +        var iterator = poll.getArgumentValidationIterator();
Dla lepszej czytelności kodu nie używaj 'var'

2023-04-25 19:51 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/scheduler/Scheduler.java
> +import org.bukkit.scheduler.BukkitTask;
Scheduler został tak stworzony, aby odgrodzić się od Bukkit API. Proszę usuń odwołania do BukkitTask, zmiast tego użyj wrappera `Task`

2023-04-25 20:20 UTC, Rollczi requested changes
Dzięki z kolejnego PR fajnie, że stosujesz się w miarę możliwości do codestyle i układu klas. 

Ogólnie słabo z hermetyzacją, jest dużo wystawianych Cache List Iterator. Sterowanie w kodzie jest bardzo pomieszane: Validator zajmuje się walidacją + dodatkowo wiadomościami, formatowaniem oraz modyfikacją PollOption w Option co łamie zasady SOLID, a dokładnie https://en.wikipedia.org/wiki/Single-responsibility_principle. Też wydaje się, że controller przejmuje za dużo odpowiedzialności związanych z logiką walidacją i startowaniem tasków polla które powinny być bardziej w warstwie managera.

Najpierw popraw to co jest do poprawy w review (nie chce Ci mieszać), później będzie trzeba poprawić przepływ i hermetyzację kodu. Jeśli chcesz mogę się wczepić i pomóc z tym albo mogę w next review wszystko wypisać ale będzie tego sporo.

2023-04-25 20:20 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/util/LabeledOptionUtil.java
> +    public static class LabeledOption<T> {
no ogólnie klasa mało sensowna ledwo co żyje w runtime bo za chwilę jest mapowana na PollOption, raczej wystarczy tylko PollOption

2023-04-26 05:41 UTC, failutee commented
> Dzięki z kolejnego PR fajnie, że stosujesz się w miarę możliwości do codestyle i układu klas.
> 
> Ogólnie słabo z hermetyzacją, jest dużo wystawianych Cache List Iterator. Sterowanie w kodzie jest bardzo pomieszane: Validator zajmuje się walidacją + dodatkowo wiadomościami, formatowaniem oraz modyfikacją PollOption w Option co łamie zasady SOLID, a dokładnie https://en.wikipedia.org/wiki/Single-responsibility_principle. Też wydaje się, że controller przejmuje za dużo odpowiedzialności związanych z logiką walidacją i startowaniem tasków polla które powinny być bardziej w warstwie managera.
> 
> Najpierw popraw to co jest do poprawy w review (nie chce Ci mieszać), później będzie trzeba poprawić przepływ i hermetyzację kodu. Jeśli chcesz mogę się wczepić i pomóc z tym albo mogę w next review wszystko wypisać ale będzie tego sporo.

O fajnie by było jak byś się wczepił mam spore zaległości jeśli chodzi o Jave wiec mógłbym się trochę poduczyć i zobaczyć jak ma to wyglądać poprawnie, dzisiaj albo jutro poprawie te rzeczy które mi wypisaliście. Jeśli chodzi o tą klasę „LabeledOption” to faktycznie trochę bez sensu ale chciałem zrobić to trochę inaczej i finalnie wyszło jak wyszło.

2023-04-30 12:56 UTC, closed without merging

2023-04-30 13:06 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    void executeCheck(Player player, @Arg UUID uuid) {
Po co ten koment jak to już zamknięte