Chat polls system.
EternalCodeTeam/EternalCore pull request #432
Opened 2023-04-30 16:44 UTC by Rollczi

2023-04-30 21:38 UTC, failutee requested changes

2023-04-30 21:38 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +@Permission("eternalcore.poll")
```suggestion
@Permission("eternalcore.poll")
@FeatureDocs(
    name = "PollSystem",
    description = "It manages and allows you to create any poll you want"
)
```

2023-04-30 21:38 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    @Execute(required = 0)
```suggestion
    @Execute(required = 0)
    @DescriptionDocs(description = "Vote for the current poll")
```

2023-04-30 21:38 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    @Route(name = "create")
```suggestion
    @Route(name = "create")
    @DescriptionDocs(description = "Create new poll", arguments = "<poll name> <duration>")
```

2023-04-30 21:38 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    @Route(name = "cancel")
```suggestion
    @Route(name = "cancel")
    @DescriptionDocs(description = "Cancel creating new poll")
```

2023-04-30 21:38 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    @Route(name = "check")
```suggestion
    @Route(name = "check")
    @DescriptionDocs(description = "Check poll results")
```

2023-05-01 09:08 UTC, Jakubk15 requested changes
Dobra robota

2023-05-01 09:08 UTC, Jakubk15 commented on eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> +        public Notification cantCancelPoll = Notification.chat("<red>✘ <dark_red>Nie możesz anulować ankiety bo żadnej nie tworzysz!");
```suggestion
        public Notification cantCancelPoll = Notification.chat("<red>✘ <dark_red>Nie możesz anulować ankiety, ponieważ żadnej nie tworzysz!");
```

2023-05-01 09:08 UTC, Jakubk15 commented on eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> +        public Notification optionsValidationMessage = Notification.chat("<newline><green>► <white>Konfigurujesz teraz 'Liste Opcji' <newline><green>► <gray>Przykładowe opcje: 'Opcja Pierwsza, Opcja
```suggestion
        public Notification optionsValidationMessage = Notification.chat("<newline><green>► <white>Konfigurujesz teraz listę opcji. <newline><green>► <gray>Przykładowe opcje: 'Opcja Pierwsza, Opcja Druga'");
```

2023-05-01 09:08 UTC, Jakubk15 commented on eternalcore-core/src/main/java/com/eternalcode/core/util/Preconditions.java
> +    private Preconditions() {
Możesz także wyrzucić UnsupportedOperationException, tak jak robimy to w przypadku innych utility klas.

2023-05-01 09:14 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/command/argument/UuidArgument.java
> +public class UuidArgument extends AbstractViewerArgument<UUID> {
Po zakończeniu ankiety wyświetla się na chacie wiadomość z hoverem który wywołuje komende /poll check (uuid) tylko po to jest ta komenda stworzona

2023-05-01 09:39 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCreateController.java
> +            .orElseThrow(() -> new NullPointerException("User cannot be null!"));
user powinien istnieć w tym kontekście i jest to nieoczekiwane zachowanie całego pluginu

2023-05-01 09:40 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCreateController.java
> +            .orElseThrow(() -> new NullPointerException("User cannot be null!"));
W takim przypadku istnieje błąd w systemie userów i nie ma to nic wspólnego z działaniem polla

2023-05-01 10:04 UTC, Jakubk15 commented on eternalcore-core/src/main/java/com/eternalcode/core/command/argument/UuidArgument.java
> +public class UuidArgument extends AbstractViewerArgument<UUID> {
Rozumiem, a nie lepiej byłoby poprostu zapisywać to jako jakiś int poprzedzony znakiem #?

2023-05-01 10:11 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/command/argument/UuidArgument.java
> +public class UuidArgument extends AbstractViewerArgument<UUID> {
Ogólnie Uuid argument jest do wywalenia bo zrobiłem po prostu nazwę ankiety

2023-05-01 11:23 UTC, Osnixer approved these changes

2023-05-01 11:23 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    }
Pool? Pool - Basen
Poll - Ankieta

2023-05-01 11:28 UTC, failutee requested changes

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +        this.pollManager.startCreatingPool(player.getUniqueId(), name, duration);
```suggestion
        this.pollManager.startCreatingPoll(player.getUniqueId(), name, duration);
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +    void executeCreate(Player player, @Arg @Suggest("pool_name") String name, @Arg Duration duration) {
```suggestion
    void executeCreate(Player player, @Arg @Suggest("poll_name") String name, @Arg Duration duration) {
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +        this.pollManager.cancelCreatingPool(player.getUniqueId());
```suggestion
        this.pollManager.cancelCreatingPoll(player.getUniqueId());
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCommand.java
> +        public static final String KEY = "pool";
```suggestion
        public static final String KEY = "poll";
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCreateController.java
> +            this.pollManager.cancelCreatingPool(uniqueId);
```suggestion
            this.pollManager.cancelCreatingPoll(uniqueId);
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCreateController.java
> +        this.pollManager.startPool(user, poll);
```suggestion
        this.pollManager.startPoll(user, poll);
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollCreateController.java
> +        this.pollManager.cancelCreatingPool(player.getUniqueId());
```suggestion
        this.pollManager.cancelCreatingPoll(player.getUniqueId());
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollManager.java
> +    public void startCreatingPool(UUID player, String name, Duration duration) {
```suggestion
    public void startCreatingPoll(UUID player, String name, Duration duration) {
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollManager.java
> +    public void cancelCreatingPool(UUID player) {
```suggestion
    public void cancelCreatingPoll(UUID player) {
```

2023-05-01 11:28 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/poll/PollManager.java
> +    public void startPool(User owner, Poll poll) {
```suggestion
    public void startPoll(User owner, Poll poll) {
```

2023-05-01 11:34 UTC, failutee approved these changes

2023-05-01 12:35 UTC, Jakubk15 approved these changes

2023-05-01 12:36 UTC, Jakubk15 commented
Dobra robota @failutee i @Rollczi 👍

2023-05-01 12:49 UTC, Hyd3r1 approved these changes
Dla mnie wygląda to dobrze

2023-05-02 13:21 UTC, Kamicjusz approved these changes

2023-05-27 10:14 UTC, Osnixer approved these changes

2023-05-29 19:13 UTC, vLuckyyy requested changes
napraw konflikt

2023-06-18 15:47 UTC, vLuckyyy approved these changes

2023-06-18 16:38 UTC, vLuckyyy requested changes
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/1f0404af-3735-413d-85cb-7eafdb4c12c6

Proszę to naprawić.

2023-12-13 03:57 UTC, closed without merging