Hotfix
EternalCodeTeam/EternalCore pull request #437
Opened 2023-05-07 18:06 UTC by failutee

Resolves #436

2023-05-07 18:13 UTC, Jakubk15 approved these changes

2023-05-07 19:34 UTC, Rollczi requested changes
Git ale ten sam błąd występuje jeszcze na 44 i 84 linii, popraw i merge.

2023-05-10 14:48 UTC, vLuckyyy approved these changes

2023-05-10 14:56 UTC, Rollczi approved these changes

2023-05-10 23:55 UTC, merged