Notice
EternalCodeTeam/EternalCore pull request #446
Opened 2023-06-18 23:49 UTC by Rollczi

New feature:
- support sound
- support hide title

New notice API:
![image](https://github.com/EternalCodeTeam/EternalCore/assets/49173834/775d0a93-9c07-433f-9e97-0573f623011a)

Examples
```yml
empty: []

oneLineChat: "Hello world"

multiLineChat:
  - "Hello"
  - "world"

onJoin:
  title: "Hello world"
  subtitle: "Subtitle"
  times: "1s 2s 1s"
  
onDeath:
  subtitle: "Subtitle"
  chat: "Death message"
  
multiChat:
  actionbar: "Hello world"
  chat:
    - "Hello"
    - "world"

onQuit:
  actionbar: "Hello world"
  sound: "PLAYER_LEVELUP 2.0 1.0"

onOtherAction:
  titleHide: true
```

2023-06-19 00:00 UTC, vLuckyyy requested changes
konflikty trzeba naprawic, a tak po za tym to mi sie podoba

2023-06-19 00:30 UTC, vLuckyyy requested changes
Wszystkie `In` zostały zmienione na `fadeIn` troche wypisałem, ale przydałoby się poprawić.

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
> +        plugin.getLogger().info("Successfully loaded EternalCore fadeIn " + millis + "ms");
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreCommand.java
> +    private static final String RELOAD_MESSAGE = "<b><gradient:#29fbff:#38b3ff>EternalCore:</gradient></b> <green>Configuration has ben successfully reloaded fadeIn %d ms.</green>";
Tutaj to samo, czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PlaceholdersConfiguration.java
> +        "# Remember that it only works fadeIn EternalCore!"
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> +        "# If you need help with the configuration or have any questions related to EternalCore, join us fadeIn our discord, or create an issue on our GitHub.",
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> +        @Description({ " ", "# Time of teleportation time fadeIn /tpa commands" })
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> +        @Description({ " ", "# Chat delay to send next message fadeIn chat" })
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> +        @Description({ " ", "# The default item give amount, when no amount is specified fadeIn the command." })
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/database/DatabaseManager.java
> +        this.logger.info("Loaded database " + databaseType.toString().toLowerCase() + " fadeIn " + stopwatch.elapsed(TimeUnit.MILLISECONDS) + "ms");
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/EnchantCommand.java
> +    @DescriptionDocs(description = "Enchants item fadeIn hand", arguments = "<enchantment> <level>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/HatCommand.java
> +    @DescriptionDocs(description = "Puts item fadeIn hand on head")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemFlagCommand.java
> +    @DescriptionDocs(description = "Adds or removes item flag from item fadeIn hand", arguments = "<item-flag>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemFlagCommand.java
> +    @DescriptionDocs(description = "Clears all item flags from item fadeIn hand")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
> +    @DescriptionDocs(description = "Sets lore of item fadeIn hand", arguments = "<line> <messages>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
> +    @DescriptionDocs(description = "Sets lore of item fadeIn hand", arguments = "<line> <messages>")
ino better `text` ponieważ lore itemu to nie wiadomość, tylko napis

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
> +    @DescriptionDocs(description = "Clears lore of item fadeIn hand")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemNameCommand.java
> +    @DescriptionDocs(description = "Clears name of item fadeIn hand")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemNameCommand.java
> +    @DescriptionDocs(description = "Sets name of item fadeIn hand", arguments = "<name>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/RepairCommand.java
> +    @DescriptionDocs(description = "Repairs item fadeIn hand")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/RepairCommand.java
> +    @DescriptionDocs(description = "Repairs all items fadeIn inventory")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/RepairCommand.java
> +    @DescriptionDocs(description = "Repairs all items fadeIn armor")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
> +    @DescriptionDocs(description = "Kills all mobs fadeIn 2 chunks around you")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
> +    @DescriptionDocs(description = "Kills all mobs fadeIn specified chunks around you", arguments = "<chunks>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
> +    @DescriptionDocs(description = "Kills specified mob fadeIn specified chunks around you", arguments = "<chunks> <mobType>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/time/DayCommand.java
> +    @DescriptionDocs(description = "Sets time to day fadeIn specified world", arguments = "<world>")
Czemu to się zmieniło na `fadeIn`?

2023-06-19 00:30 UTC, vLuckyyy commented on eternalcore-core/src/test/java/com/eternalcode/core/notice/PlatformBroadcasterAdventureImplTest.java
> +        mockAudience.assertMessage("Siema siema o teh poże każdy łep lakiemu odstrzelić może");
fajne

2023-06-19 08:52 UTC, vLuckyyy approved these changes
Reszta chyba git, jak znajdę błąd to napisze

2023-06-19 08:53 UTC, vLuckyyy commented
Ponadto poprawie od siebie komentarze dot. Notification w domu.

2023-06-20 22:35 UTC, Osnixer approved these changes

2023-06-20 22:35 UTC, Osnixer commented on eternalcore-core/src/main/java/com/eternalcode/core/notice/NoticeService.java
> +    private final PlatformBroadcaster announcer;
announcer -> broadcaster

2023-06-20 22:35 UTC, Osnixer commented on eternalcore-core/src/test/java/com/eternalcode/core/test/MockAudienceProvider.java
> +import java.util.*;
-import all

2023-06-21 20:54 UTC, merged