GH-375 Add automessage system
EternalCodeTeam/EternalCore pull request #449
Opened 2023-06-22 21:55 UTC by Osnixer

2023-06-22 22:48 UTC, Rollczi requested changes

2023-06-22 22:48 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/database/wrapper/AutoMessageRepositoryOrmLite.java
> +            .queryForFirst() == null);
```suggestion
        return this.selectSafe(AutoMessageIgnoreWrapper.class, uuid)
            .thenApply(option -> option.isEmpty());
```

2023-06-22 22:50 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageCommand.java
> +                    .send();
```suggestion
                this.noticeService.player(player.getUniqueId(), messages -> messages.autoMessage().enabled());
```

2023-06-22 22:50 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageCommand.java
> +        });
```suggestion
            this.noticeService.player(player.getUniqueId(), (messages -> messages.autoMessage().disabled();)
        });
```

2023-06-22 22:53 UTC, Rollczi approved these changes

2023-06-22 23:23 UTC, vLuckyyy approved these changes

2023-06-23 13:30 UTC, eripe14 approved these changes

2023-06-23 14:54 UTC, Kamicjusz approved these changes

2023-06-23 15:08 UTC, igoyek approved these changes

2023-06-23 15:31 UTC, merged