Add option to set specific world to random teleport feature
EternalCodeTeam/EternalCore pull request #543
Opened 2023-09-25 20:41 UTC by ChudziudgiToJa

Fixes #540

2023-09-25 20:55 UTC, vLuckyyy approved these changes

2023-09-25 22:13 UTC, Osnixer approved these changes
Fajniutko dobra robota

2023-09-26 07:09 UTC, Rollczi requested changes
Fajnie, że jest rozwiązanie na ten problem i w przyszłości fajnie byłoby zrobić trochę bardziej rozbudowaną konfigurację tak, aby obsługiwać przypadek z np. CraftHype.pl
Gdzie jest potrzebne przekierowanie z jednego świata, a nie z wszystkich.
Zastosuj się do poprawki z null checkiem i gitówa

2023-09-26 07:09 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
> +        }
null check:
```suggestion
        if (!this.randomTeleportSettings.randomTeleportWorld().isBlank()) {
            world = this.server.getWorld(this.randomTeleportSettings.randomTeleportWorld());
            
            if (world == null) {
                throw new IllegalStateException("World " + this.randomTeleportSettings.randomTeleportWorld() + "is not exists!");
            }
        }
```

2023-09-26 07:24 UTC, ChudziudgiToJa commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
> +        }
Działa bez problemu testowane było

2023-09-26 07:26 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
> +        }
Tutaj chodziło że kos który napisał ci rollczi nie zadziała, bo nie ma w nim import, więc musisz ręcznie dodać

2023-10-02 18:33 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
> +                throw new IllegalStateException("World " + this.randomTeleportSettings.randomTeleportWorld() + "is not exists!");
```suggestion
                throw new IllegalStateException("World " + this.randomTeleportSettings.randomTeleportWorld() + " is not exists!");
```

2023-10-02 18:34 UTC, Rollczi approved these changes

2023-10-02 18:38 UTC, merged