Prevent vanished players being marked as AFK
EternalCodeTeam/EternalCore pull request #550
Opened 2023-10-15 17:07 UTC by rchomczyk

## Description

Prevent vanished players being marked as AFK. 

## Note

It should work with most of the plugins for vanish functionality, as it is being resolved with use of commonly established standard. I have tested the plugin with use of SuperVanish and it seems to work fine.

2023-10-15 18:36 UTC, vLuckyyy approved these changes

2023-10-16 19:45 UTC, Rollczi requested changes

2023-10-16 19:45 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/vanish/VanishService.java
> +            .orElse(false);
Don't use optional in this case

2023-10-16 19:45 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/vanish/VanishService.java
> +        return vanished;
initialization of `boolean vanished = false;` is const 
```suggestion
        for (MetadataValue isVanished : player.getMetadata(METADATA_VANISHED_KEY)) {
            if (isVanished.asBoolean()) {
                return true;
            }
        }
        
        return false;
```

2023-10-16 19:48 UTC, Rollczi approved these changes

2023-10-16 19:49 UTC, merged