GH-602 Use Location Argument in tppos.
EternalCodeTeam/EternalCore pull request #604
Opened 2023-12-25 15:36 UTC by vLuckyyy

Fixes: GH-602

2023-12-25 21:40 UTC, P1otrulla approved these changes

2023-12-26 10:58 UTC, imDMK requested changes

2023-12-26 10:58 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportToPositionCommand.java
> +            .placeholder("{Y}", String.valueOf(location.getZ()))
```suggestion
            .placeholder("{Y}", String.valueOf(location.getY()))
```

2023-12-26 10:58 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportToPositionCommand.java
> +            .placeholder("{Y}", String.valueOf(location.getZ()))
```suggestion
            .placeholder("{Y}", String.valueOf(location.getY()))
```

2023-12-26 17:11 UTC, igoyek approved these changes

2023-12-26 17:14 UTC, SfenKer approved these changes

2023-12-26 21:28 UTC, Rollczi approved these changes

2023-12-26 22:18 UTC, imDMK approved these changes

2023-12-26 22:18 UTC, merged