Add PlayerArgument, fix /tp command usage.
EternalCodeTeam/EternalCore pull request #608
Opened 2023-12-25 20:56 UTC by vLuckyyy

Fix #601

2023-12-25 21:39 UTC, P1otrulla approved these changes

2023-12-26 10:57 UTC, imDMK approved these changes

2023-12-26 17:13 UTC, igoyek approved these changes

2023-12-26 17:16 UTC, SfenKer approved these changes

2023-12-26 17:29 UTC, Jakubk15 approved these changes

2023-12-26 21:31 UTC, Rollczi requested changes

2023-12-26 21:31 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java
> +    void to(@Context Viewer sender, @Arg Player target, @Arg Location location) {
missing world argument, I think we can  use optional world argument

2023-12-26 21:31 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java
> +    void to(@Context Player sender, @Arg Location location) {
you can add optional world argument to the end of the tp command

2023-12-27 17:20 UTC, Rollczi approved these changes

2023-12-27 17:21 UTC, merged