Add sudo command
EternalCodeTeam/EternalCore pull request #625
Opened 2024-01-05 19:52 UTC by vLuckyyy

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to readme etc.
- [ ] My changes generate no new warnings
- [ ] I have added test to cover my changes
- [ ] I have added appropriate labels to this Pull Request

2024-01-08 07:27 UTC, CitralFlo approved these changes
LGTM. I hope it was tested with all commands

2024-01-08 08:34 UTC, igoyek approved these changes

2024-01-08 08:35 UTC, imDMK approved these changes

2024-01-09 02:57 UTC, P1otrulla approved these changes

2024-01-09 11:35 UTC, Rollczi requested changes
We can make these commands more short e.g.
`/sudo Rollczi day`
`/sudo -console day`

2024-01-09 11:35 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/sudo/SudoCommand.java
> +    @Execute(name = "console")
```suggestion
    @Execute(name = "-console")
```

2024-01-09 11:35 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/sudo/SudoCommand.java
> +    @Execute(name = "player")
```suggestion
    @Execute
```

2024-01-12 16:23 UTC, Jakubk15 approved these changes

2024-01-26 20:53 UTC, Rollczi approved these changes

2024-01-27 07:17 UTC, merged