Global versioning managment
EternalCodeTeam/EternalCore pull request #626
Opened 2024-01-06 22:04 UTC by vLuckyyy

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to readme etc.
- [ ] My changes generate no new warnings
- [ ] I have added test to cover my changes
- [ ] I have added appropriate labels to this Pull Request

2024-01-06 22:07 UTC, Rollczi requested changes

2024-01-06 22:07 UTC, Rollczi commented on eternalcore-core/build.gradle.kts
> +    compileOnly("com.eternalcode:gitcheck:${Versions.GIT_CHECK}")
```suggestion
    implementation("com.eternalcode:gitcheck:${Versions.GIT_CHECK}")
```

2024-01-06 22:10 UTC, Jakubk15 approved these changes

2024-01-06 22:10 UTC, Jakubk15 commented on buildSrc/src/main/kotlin/Versions.kt
> +        const val PAPER_API = "1.19.4-R0.1-SNAPSHOT"
1.20 where?

2024-01-06 22:12 UTC, Rollczi commented on buildSrc/src/main/kotlin/Versions.kt
> +        const val PAPER_API = "1.19.4-R0.1-SNAPSHOT"
real

2024-01-06 22:14 UTC, Rollczi approved these changes

2024-01-06 22:17 UTC, CitralFlo approved these changes

2024-01-07 14:32 UTC, P1otrulla approved these changes

2024-01-07 22:06 UTC, imDMK approved these changes

2024-01-07 22:07 UTC, merged