Add delay to RandomTeleport, add corresponding lines of text
EternalCodeTeam/EternalCore pull request #631
Opened 2024-01-10 13:48 UTC by CitralFlo

2024-01-10 13:54 UTC, vLuckyyy approved these changes

2024-01-10 13:54 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> +        public Duration randomTeleportDelay = Duration.ofSeconds(15);
I suggest a default value `60s`.

2024-01-10 13:54 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportCommand.java
> +        }
Since this code is repeated in 2 places, it should have a single method for checking whether the player is in cooldown.

2024-01-10 13:54 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> +        public Notice randomTeleportDelay = Notice.chat("<red>✘ <dark_red>Błąd: <red>Możesz użyć tej komendy dopiero za <dark_red>{TIME}!");
```suggestion
        @Description({ " ", "# {TIME} - Czas do następnego użycia komendy (cooldown)" })
        public Notice randomTeleportDelay = Notice.chat("<red>✘ <dark_red>Błąd: <red>Możesz skorzystać z losowej teleportacji dopiero za <dark_red>{TIME}!");
```

2024-01-10 13:54 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
> +        public Notice randomTeleportDelay = Notice.chat("<red>✘ <dark_red>You can use this command only after <red>{TIME}!");
```suggestion
        @Description({ " ", "# {TIME} - Time to next use (cooldown)" })
        public Notice randomTeleportDelay = Notice.chat("<red>✘ <dark_red>You can use random teleport after <red>{TIME}!");
```

2024-01-10 14:06 UTC, vLuckyyy requested changes

2024-01-10 14:06 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportCommand.java
> +    private boolean hasRTPDelay(UUID uuid) {
Change name to: `hasRandomTeleportDelay`

2024-01-11 01:17 UTC, P1otrulla approved these changes
gj

2024-01-11 07:11 UTC, imDMK approved these changes

2024-01-11 12:48 UTC, vLuckyyy approved these changes

2024-01-11 13:34 UTC, merged