RandomTeleport API implementation
EternalCodeTeam/EternalCore pull request #671
Opened 2024-02-05 17:28 UTC by igoyek

2024-02-05 17:31 UTC, VerniQ approved these changes

2024-02-05 17:37 UTC, VerniQ approved these changes

2024-02-05 17:58 UTC, Rollczi requested changes

2024-02-05 17:58 UTC, Rollczi commented on eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
> +    boolean isSafeLocation(Chunk chunk, Location location);
Ta metoda w niepowołanych rękach jest blokującą i nie powinna zostać wystawiona.

2024-02-05 17:58 UTC, Rollczi commented on eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/event/RandomTeleportEvent.java
> +    private boolean cancelled;
Że co proszę

2024-02-05 17:58 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportCommand.java
> +    private final RandomTeleportServiceImpl randomTeleportServiceImpl;
Use interface instead class impl

2024-02-05 20:05 UTC, Rollczi commented on eternalcore-api-example/src/main/java/com/eternalcode/example/feature/randomteleport/ApiRandomTeleportCommand.java
> +    @Execute(name = "get-safe-random-location-with-attempts")
```suggestion
    @Execute(name = "safe-random-location")
```

2024-02-05 20:05 UTC, Rollczi commented on eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportType.java
>      STATIC_RADIUS,
revert to core module

2024-02-05 20:20 UTC, Rollczi approved these changes

2024-02-06 08:30 UTC, Jakubk15 approved these changes

2024-02-06 09:07 UTC, P1otrulla approved these changes

2024-02-06 10:33 UTC, merged