Standarize code style in events used in developer api.
EternalCodeTeam/EternalCore pull request #689
Opened 2024-02-15 09:23 UTC by vLuckyyy

2024-02-15 16:37 UTC, imDMK reviewed
I don't think the event HandlerList names should be changed.

2024-02-15 21:50 UTC, P1otrulla approved these changes

2024-02-15 21:54 UTC, igoyek approved these changes

2024-02-17 19:21 UTC, Rollczi requested changes
Arrange the static methods so that they are last. Revert name of static fields. (Rollczi & Piotrulla request z wczorajszej rozmowy)

2024-02-24 15:25 UTC, Rollczi approved these changes

2024-02-24 15:27 UTC, merged