Add option to kick a player for being AFK
EternalCodeTeam/EternalCore pull request #694
Opened 2024-02-17 16:21 UTC by failutee

## Description

The introduced change allows for kicking a player from the server due to being AFK.

Fixes # (issue)
#681

2024-02-17 19:56 UTC, vLuckyyy approved these changes

2024-02-17 19:56 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkController.java
> +        Player player = Bukkit.getPlayer(playerUUID);
Use Server.

2024-02-17 20:01 UTC, Rollczi requested changes

2024-02-17 20:02 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkController.java
> +    AfkController(AfkService afkService, MiniMessage miniMessage, UserManager userManager, TranslationManager translationManager, PluginConfiguration config) {
```suggestion
    AfkController(
    AfkService afkService,
    MiniMessage miniMessage,
    UserManager userManager,
    TranslationManager translationManager, 
    PluginConfiguration config
   ) {
```

2024-02-17 20:02 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkController.java
Can you make this in two classes? AfkStateController and AfkKickController?

2024-02-17 20:06 UTC, failutee commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkController.java
Sure

2024-02-18 12:03 UTC, P1otrulla approved these changes
Do what they tell you and it will be great

2024-02-18 19:15 UTC, failutee commented
Have I done something wrong? Because for me, it builds normally without any problems
@vLuckyyy

2024-02-18 19:32 UTC, vLuckyyy commented
> Have I done something wrong? Because for me, it builds normally without any problems @vLuckyyy

Fixed

2024-02-19 16:17 UTC, Rollczi approved these changes

2024-02-19 21:21 UTC, merged