GH-663 Add private chat api
EternalCodeTeam/EternalCore pull request #704
Opened 2024-02-25 18:03 UTC by vLuckyyy

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to readme etc.
- [ ] My changes generate no new warnings
- [ ] I have added test to cover my changes
- [ ] I have added appropriate labels to this Pull Request

2024-02-25 18:59 UTC, P1otrulla approved these changes

2024-02-29 07:31 UTC, Rollczi requested changes
I think we can expose morę methods from Private message service (reply() and privateMessage())

2024-02-29 07:31 UTC, Rollczi commented on eternalcore-api/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatEvent.java
> +    private final String content;
Maybe mutable ?

2024-03-10 18:38 UTC, vLuckyyy commented on eternalcore-api/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatEvent.java
> +    private final String content;
![image](https://github.com/EternalCodeTeam/EternalCore/assets/65517973/b1a66d9a-e629-4d1a-8f84-665ef4e35d1a)

2024-03-20 16:50 UTC, vLuckyyy commented
> I think we can expose morę methods from Private message service (reply() and privateMessage())

![image](https://github.com/EternalCodeTeam/EternalCore/assets/65517973/b1b74bed-aea4-408b-87ad-4f124783b95f)

![image](https://github.com/EternalCodeTeam/EternalCore/assets/65517973/e15b65b8-93a5-40fb-a46c-ead25054c13b)

2024-03-20 17:03 UTC, imDMK approved these changes

2024-03-20 17:03 UTC, imDMK commented on eternalcore-api-example/src/main/java/com/eternalcode/example/feature/privatechat/ApiPrivateChatListener.java
> +        }
This is final release?

2024-03-20 17:04 UTC, vLuckyyy commented on eternalcore-api-example/src/main/java/com/eternalcode/example/feature/privatechat/ApiPrivateChatListener.java
> +            player.sendMessage("Private Chat: " + senderPlayer.getName() + " -> " + receiverPlayer.getName() + ": " + content);
That is only an API example; no one besides the programmers manually inspecting the code on GitHub will be able to run it.

2024-03-21 05:14 UTC, Rollczi commented on eternalcore-api-example/src/main/java/com/eternalcode/example/feature/privatechat/ApiPrivateChatListener.java
> +            player.sendMessage("Private Chat: " + senderPlayer.getName() + " -> " + receiverPlayer.getName() + ": " + content);
Real, resolved

2024-03-21 05:18 UTC, Rollczi approved these changes

2024-03-21 05:18 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatServiceImpl.java
> +    public void privateMessage(Player sender, Player target, String message) {
To może trochę w przyszłości przeszkodzić w /msg przez console

2024-03-21 14:02 UTC, merged