Add homes left placeholder.
EternalCodeTeam/EternalCore pull request #726
Opened 2024-03-07 23:40 UTC by vLuckyyy

Fixes: #705

2024-03-08 06:01 UTC, imDMK approved these changes

2024-03-08 16:39 UTC, CitralFlo approved these changes
LGTM, i like the import cleanup

2024-03-09 08:44 UTC, P1otrulla approved these changes

2024-03-10 14:17 UTC, Rollczi reviewed
Rozbij to troszkę mało czytelne

2024-03-11 12:43 UTC, Rollczi requested changes

2024-03-15 11:44 UTC, vLuckyyy commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomePlaceholderSetup.java
> +        return String.valueOf(homesLimit - this.homeManager.getAmountOfHomes(targetPlayer.getUniqueId()));
i create unit test for this :D

2024-03-21 05:22 UTC, Rollczi requested changes

2024-03-21 05:22 UTC, Rollczi commented on eternalcore-core/src/test/java/com/eternalcode/core/feature/home/HomePlaceholderSetupTest.java
> +        assertEquals(expectedHomesLeft, homesLeft(homesLimit, amountOfHomes));
ten test nic nie testuje defakto. Aby testy miały jakikolwiek sens musisz odpalić część kodu eternala Tzn homemanger i te placeholders. Robisz checka == -1, a tam nawet nic nie zmieniłeś w managerze

2024-04-19 21:20 UTC, merged