GH-749 Tellraw multiple messages
EternalCodeTeam/EternalCore pull request #749
Opened 2024-04-08 15:47 UTC by CitralFlo

2024-04-08 16:05 UTC, CitralFlo commented
Due to LiteCommands not supporting sth like `@Separator` this feature has been added in few commands instead of one

2024-04-08 16:11 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawCommand.java
> +    @DescriptionDocs(description = "")
no description

2024-04-08 16:11 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawCommand.java
> +    @DescriptionDocs(description = "")
no description

2024-04-08 16:11 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawCommand.java
> +                .notice(notice.getNoticeTextType(), notice.getNoticeText())
```suggestion
        for (TellRawNotice rawNotice : this.multipleNotices) {
            this.noticeService.create()
                .notice(rawNotice.getNoticeTextType(), rawNotice.getNoticeText())
```

2024-04-08 16:11 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawNotice.java
> +    private NoticeTextType noticeTextType;
```suggestion
    private NoticeTextType noticeType;
```

2024-04-08 19:09 UTC, igoyek approved these changes

2024-04-09 17:18 UTC, imDMK requested changes

2024-04-09 17:18 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawCommand.java
> +        if (this.tellRawService.getNotices(uuid) == null || this.tellRawService.getNotices(uuid).isEmpty()) {
create a separate method in TellRawService, maybe named ```hasNotices``` and return boolean

2024-04-09 17:18 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawService.java
> +        this.multipleNotices.put(uuid, notices);
```suggestion
        Set<TellRawNotice> notices = this.multipleNotices.computeIfAbsent(uuid, k -> new HashSet<>());
        
        notices.add(notice);
```

2024-04-09 17:18 UTC, imDMK commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawNotice.java
> +record TellRawNotice(NoticeTextType noticeTextType, String message) {}
```suggestion
record TellRawNotice(NoticeTextType noticeType, String message) {}
```

2024-04-09 17:22 UTC, vLuckyyy reviewed
Hmm? 

maybe:
/tellraw -single <type>  <text>
/tellraw -multiple - star's notice queue
/tellraw -multiple-send

imo the above format is better readable. I'm opening discussions, have your say

2024-04-10 12:12 UTC, CitralFlo commented
> Hmm?
> 
> maybe: /tellraw **-single** `<type>` `<text>` /tellraw **-multiple** - star's notice queue /tellraw **-multiple-send** - sends notices from queue, but you can set up hover message with click event to make this action quicker
> 
> imo the above format is better readable. I'm opening discussions, have your say

I was thinking about NOT changing current command usage, so letting it be  like `/tellraw * chat <message>`
The other suggestions look fine, so i can stick with them.

2024-04-16 01:03 UTC, CitralFlo commented
New command structure: 
![image](https://github.com/EternalCodeTeam/EternalCore/assets/80779749/efc938a8-7e1f-46e8-bc73-60ffd531bddc)

![image](https://github.com/EternalCodeTeam/EternalCore/assets/80779749/e41fa644-7599-4e11-867b-f3d2edee402f)

2024-04-20 19:32 UTC, Jakubk15 approved these changes

2024-04-26 17:36 UTC, imDMK approved these changes

2024-04-26 18:37 UTC, Rollczi requested changes

2024-04-26 18:37 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/tellraw/TellRawMultipleCommand.java
> +    void tellRawSend(@Context Viewer sender, @Arg Player target) {
Nie rozumiem, czemu są chyba dwie identyczne metody? Tylko jedna to send a drugie to all? Nie lepiej dać po prostu send?

2024-04-26 18:42 UTC, Rollczi commented
Ja bym trochę przerobił parę komend.
Na coś w stylu:

/tellraw quote add <type> <content>
/tellraw quote clear
/tellraw quote send-all
/tellraw quote send <count>

Ogólnie myślniki używa się jako flagi ale subkomendy to średnio.

Np.
/chat off
/chat on
/chat slowmode

2024-04-28 20:42 UTC, CitralFlo commented
> quote

Firstly I don't like your proposition.
My proposition:

![image](https://github.com/EternalCodeTeam/EternalCore/assets/80779749/54ee71d0-ebef-4145-859f-95541e0cec50)

Your proposition (vLuckyyy corrected that You meant "queue"):
![image](https://github.com/EternalCodeTeam/EternalCore/assets/80779749/aa6abe82-f1c0-4698-b800-0578e8673e11)

Problem with yours will be when there are more players on the server and You cannot see "queue" part.

![image](https://github.com/EternalCodeTeam/EternalCore/assets/80779749/3a4c07ec-3e35-47f2-96f2-4062753fc735)

2024-04-30 15:01 UTC, Rollczi approved these changes

2024-04-30 22:47 UTC, merged