Auto add warp
EternalCodeTeam/EternalCore pull request #773
Opened 2024-05-08 17:33 UTC by CitralFlo

2024-05-08 17:40 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
> +            int size = warpSection.items().size() + 10;
Magic number

2024-05-08 17:49 UTC, Rollczi approved these changes

2024-05-08 19:34 UTC, CitralFlo commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
> +                        .withLore(Collections.singletonList("<gray>Click to teleport!"))
This is default option iguess. everything is configurable inside translation files.

2024-05-09 11:27 UTC, Rollczi commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
> +                        .withLore(Collections.singletonList("<gray>Click to teleport!"))
Yup, Mike is right

2024-05-12 13:34 UTC, CitralFlo commented on eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
> +                        .withLore(Collections.singletonList("<gray>Click to teleport!"))
Added default options in config for players to customize quick warp adding.

2024-05-23 18:07 UTC, vLuckyyy commented
> First:
> 
> When i open empty gui:
> 
> ```shell
> [20:05:12 INFO]: vlucky_dev issued server command: /warp
> [20:05:12 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
> [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
> [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
> [20:05:12 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:421)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:412)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:143)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createBorder(WarpInventory.java:101)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createInventory(WarpInventory.java:91)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.openInventory(WarpInventory.java:197)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.command.WarpCommand.warp(WarpCommand.java:57)
> [20:05:12 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> [20:05:12 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:100)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:90)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecutorMatchResult.executeCommand(CommandExecutorMatchResult.java:22)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$3(CommandExecuteService.java:179)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.tryRun(BukkitSchedulerImpl.java:74)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplySync(BukkitSchedulerImpl.java:46)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplyLater(BukkitSchedulerImpl.java:28)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.scheduler.Scheduler.supply(Scheduler.java:52)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:177)
> [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:157)
> [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute0(CommandExecuteService.java:122)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:62)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.CommandManager$PlatformListener.execute(CommandManager.java:63)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitCommand.execute(BukkitCommand.java:50)
> [20:05:12 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86)
> [20:05:12 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:349)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:336)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:331)
> [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
> [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
> [20:05:12 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
> [20:05:12 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
> [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.poll [...]

2024-05-23 18:09 UTC, vLuckyyy commented
> > First:
> > When i open empty gui:
> > ```shell
> > [20:05:12 INFO]: vlucky_dev issued server command: /warp
> > [20:05:12 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
> > [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
> > [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
> > [20:05:12 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> > [20:05:12 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
> > [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:421)
> > [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:412)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:143)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createBorder(WarpInventory.java:101)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createInventory(WarpInventory.java:91)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.openInventory(WarpInventory.java:197)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.command.WarpCommand.warp(WarpCommand.java:57)
> > [20:05:12 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> > [20:05:12 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:100)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:90)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecutorMatchResult.executeCommand(CommandExecutorMatchResult.java:22)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$3(CommandExecuteService.java:179)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.tryRun(BukkitSchedulerImpl.java:74)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplySync(BukkitSchedulerImpl.java:46)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplyLater(BukkitSchedulerImpl.java:28)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.scheduler.Scheduler.supply(Scheduler.java:52)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:177)
> > [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:157)
> > [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute0(CommandExecuteService.java:122)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:62)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.CommandManager$PlatformListener.execute(CommandManager.java:63)
> > [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitCommand.execute(BukkitCommand.java:50)
> > [20:05:12 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86)
> > [20:05:12 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> > [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> > [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> > [20:05:12 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> > [20:05:12 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> > [20:05:12 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> > [20:05:12 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442)
> > [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:349)
> > [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:336)
> > [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:331)
> > [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
> > [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
> > [20:05:12 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> > [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
> > [20:05:12 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> > [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
> > [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
> > [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
> > [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.pollTa [...]

2024-05-23 21:04 UTC, CitralFlo commented
@vLuckyyy all issues adressed, can You test that again???

2024-06-09 17:42 UTC, vLuckyyy requested changes
Waiting to resolve all errors.

2024-06-29 22:24 UTC, CitralFlo commented
> First:
> 
> When i open empty gui:
> 
> ```shell
> [20:05:12 INFO]: vlucky_dev issued server command: /warp
> [20:05:12 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
> [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
> [20:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
> [20:05:12 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:421)
> [20:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:412)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:143)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createBorder(WarpInventory.java:101)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.createInventory(WarpInventory.java:91)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.WarpInventory.openInventory(WarpInventory.java:197)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.feature.warp.command.WarpCommand.warp(WarpCommand.java:57)
> [20:05:12 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> [20:05:12 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:100)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.annotations.MethodCommandExecutor$FinalCommandExecutor.get(MethodCommandExecutor.java:90)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecutorMatchResult.executeCommand(CommandExecutorMatchResult.java:22)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$3(CommandExecuteService.java:179)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.tryRun(BukkitSchedulerImpl.java:74)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplySync(BukkitSchedulerImpl.java:46)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitSchedulerImpl.supplyLater(BukkitSchedulerImpl.java:28)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.scheduler.Scheduler.supply(Scheduler.java:52)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:177)
> [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.lambda$execute$4(CommandExecuteService.java:157)
> [20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)[20:05:12 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute0(CommandExecuteService.java:122)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:62)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.command.CommandManager$PlatformListener.execute(CommandManager.java:63)
> [20:05:12 WARN]:        at EternalCore v1.2.1 (MC 1.17.x-1.20.x).jar//com.eternalcode.core.libs.dev.rollczi.litecommands.bukkit.BukkitCommand.execute(BukkitCommand.java:50)
> [20:05:12 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86)
> [20:05:12 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
> [20:05:12 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:349)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:336)
> [20:05:12 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:331)
> [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
> [20:05:12 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
> [20:05:12 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
> [20:05:12 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
> [20:05:12 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
> [20:05:12 WARN]:        at net.minecraft.server.MinecraftServer.poll [...]

2024-06-29 22:25 UTC, CitralFlo commented
Other errors related to Minecraft 1.21 acting up.

2024-07-01 00:29 UTC, vLuckyyy approved these changes

2024-07-01 00:31 UTC, merged